modLoader="javafml"
loaderVersion="[4,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="extra_handles"
version="1.0.0"
displayName="Extra Handles"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Spiderman31807"
authors="Spiderman31807"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.extra_handles]]
modId="neoforge"
type="required"
versionRange="[21.1.176,)"
ordering="AFTER"
side="BOTH"

[[dependencies.extra_handles]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"




# Start of user code block dependencies configuration
[[mixins]]
config="mixin.extra_handles.json"
# End of user code block dependencies configuration
